// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CJsGQzTyjtp_OelzHQk2IFDeL1n82-M',
    appId: '1:1036749505666:web:8d44e3ef1ccbc7c29ea09b',
    messagingSenderId: '1036749505666',
    projectId: 'food-recipe-app-d37ce',
    authDomain: 'food-recipe-app-d37ce.firebaseapp.com',
    storageBucket: 'food-recipe-app-d37ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDesbchzaqD6jFeAKPwqnnC1KASh-7SLDY',
    appId: '1:1036749505666:android:c14f486b88b4ce199ea09b',
    messagingSenderId: '1036749505666',
    projectId: 'food-recipe-app-d37ce',
    storageBucket: 'food-recipe-app-d37ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjvUjlL-CWprxg7imT97Y_LevhqQGo8w',
    appId: '1:1036749505666:ios:6c01ab6f4507803a9ea09b',
    messagingSenderId: '1036749505666',
    projectId: 'food-recipe-app-d37ce',
    storageBucket: 'food-recipe-app-d37ce.firebasestorage.app',
    iosBundleId: 'com.example.assignment3RecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjvUjlL-CWprxg7imT97Y_LevhqQGo8w',
    appId: '1:1036749505666:ios:6c01ab6f4507803a9ea09b',
    messagingSenderId: '1036749505666',
    projectId: 'food-recipe-app-d37ce',
    storageBucket: 'food-recipe-app-d37ce.firebasestorage.app',
    iosBundleId: 'com.example.assignment3RecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CJsGQzTyjtp_OelzHQk2IFDeL1n82-M',
    appId: '1:1036749505666:web:79a2745bbc005dfb9ea09b',
    messagingSenderId: '1036749505666',
    projectId: 'food-recipe-app-d37ce',
    authDomain: 'food-recipe-app-d37ce.firebaseapp.com',
    storageBucket: 'food-recipe-app-d37ce.firebasestorage.app',
  );
}
